@startuml slave
!theme plain

Waiting : Waiting for a proposal from a client\nor operation from the leader
SendToLoader : Send the proposal to the loader
'AddToQueue : Add operation to the queue (I)
Elaboration : Elaborate the operation
WaitingOrder : Waiting for the order from the leader
Complain : Complain to the leader
Commit : Commit the operation
Abort : Abort the operation
Rollback : Rollback to the previous state
FixFaultyValue : Fix the result according to the leader
NewSieveConfig : If new leader of the new sieve config is self, broadcast the new sieve config
NewSieveConfigValidation : Wait for new sieve config validation messages
ValidationOrder : Validate the operation result and send the validation message to the leader
WaitingLeaderValidation : Wait for the leader final result


[*] --> Waiting

Waiting --> SendToLoader: [Received proposal]

SendToLoader --> Waiting

Waiting --> Elaboration : [Received operation\nfrom the leader]

'Waiting --> AddToQueue : [Received operation\nfrom the leader]

'AddToQueue --> Elaboration

Elaboration --> WaitingOrder : [Operation executed. Send approval to leader]

WaitingOrder --> Complain : [Leader took too long to respond]

'WaitingOrder --> Commit : [Received order confirm]

WaitingOrder --> ValidationOrder : [Received order to validate the operation output]

ValidationOrder --> WaitingLeaderValidation

WaitingLeaderValidation --> Commit : [Received leader commit]

WaitingLeaderValidation --> Abort : [Received leader abort]

'WaitingOrder --> Abort : [Receiver order abort]

WaitingLeaderValidation --> FixFaultyValue : [Received order to fix the operation output]

FixFaultyValue --> Commit

Commit --> Waiting : [Received commit confirm]

Abort --> Rollback

Complain --> Waiting

Rollback --> Waiting

Waiting -->NewSieveConfig : [Received new sieve config]

NewSieveConfig --> Waiting : [If the process is not the leader]

NewSieveConfig --> NewSieveConfigValidation

NewSieveConfigValidation --> Waiting : [If the majority of validation messages disagree]

NewSieveConfigValidation --> [*] : [If the majority of validation messages agree with self as new leader]

Waiting --> Closing

Closing --> [*]
@enduml